### ISSUE TITLE
资产推送问题，获取不到uid

### ISSUE THREAD

**Issue by GitLiyc** [kolikow/ele#1]
你好大佬，问什么创建了一个变量cookie 值为unb=22。。。。。。;cookie2=11f3。。。。。。;USERID=7。。。。;SID=M。。。。;wxUid=UID_n。。。。。
日志显示这样
乐园币：65
当前乐园币：65
总吃货豆：443
余额：异常
没有获取到推送 uid，不推送消息

**Comment by YuPlusE** [comment]
wxUid后面记得加英文的分号

**Comment by YuPlusE** [comment]
Duplicate of # @GitLiyc 
wxUid后面记得加英文的分号

**Comment by GitLiyc** [comment]
> Duplicate of # @GitLiyc wxUid后面记得加英文的分号

可是还是不行，还有检验ck的也不好使
🔔饿了么CK检测, 开始!
饿了么登录地址：elm.188855.xyz

开始检测【账号1】
TypeError: Cannot read properties of null (reading '1')
    at /ql/scripts/yupluse_elm/elm_checkCK.js:12:11260
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

## 执行结束... 2024-06-11 11:45:31 耗时 0 秒
基本上该配置的变量都写了
elmck
appToken
myUid
cookie
tunnel

**Comment by GitLiyc** [comment]
> Duplicate of # @GitLiyc wxUid后面记得加英文的分号

![Uploading d1bd6a6a5463c2cd8aea6d99624ec65.png…]()

**Comment by YuPlusE** [comment]
Duplicate of # @GitLiyc 
还是wxUid的问题，再检查一下吧
