### ISSUE TITLE
大佬cookie跟环境变量该怎么设置。

### ISSUE THREAD

**Issue by amadeus5201** [kolikow/ele#2]
大佬cookie跟环境变量该怎么设置。

**Comment by YuPlusE** [comment]
青龙面板-环境变量：elmck

推送 wxpush，要求 elmck 里面有 wxUid,如'unb=xxx;cookie2=xxxUSERID=xx;SID=xxx;wxUid=xx;'
在ele_sendNotify.js中配置wxpusher的apptoken

检测CK，要求环境变量或配置文件有
export appToken='AT_xxx' #wxpusher的appToken
export myUid='UID_xxx' #自己的uid，接收通知
export tunnel='elm.xxx.xyz' #掉线重新登录地址

**Comment by YuPlusE** [comment]
Duplicate of # @amadeus5201 
青龙面板-环境变量：elmck

推送 wxpush，要求 elmck 里面有 wxUid,如'unb=xxx;cookie2=xxxUSERID=xx;SID=xxx;wxUid=xx;'
在ele_sendNotify.js中配置wxpusher的apptoken

检测CK，要求环境变量或配置文件有
export appToken='AT_xxx' #wxpusher的appToken
export myUid='UID_xxx' #自己的uid，接收通知
export tunnel='elm.xxx.xyz' #掉线重新登录地址

**Comment by amadeus5201** [comment]
谢谢大佬其他都懂了，掉线重新登陆地址这个怎么获取呀

**Comment by YuPlusE** [comment]
Duplicate of # @amadeus5201 
你自己登录面板的地址
